tx.py: fix TypeError when splitting byte string (python3 compatibility)
python2.7:
```python
>>> count = 12345678
>>> data = pack('<I', count)
>>> toSend = [int(binascii.hexlify(x),16) for x in data]
>>> toSend
[78, 97, 188, 0]
```

python3.8:
```python
>>> count = 12345678
>>> data = pack('<I', count)
>>> toSend = [int(binascii.hexlify(x),16) for x in data]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
TypeError: a bytes-like object is required, not 'int'
>>> toSend = list(data)
>>> toSend
[78, 97, 188, 0]
```